# Generated by Django 4.0.5 on 2022-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.jpg', height_field=900, upload_to='static/img/profile', width_field=600),
        ),
    ]
