# Generated by Django 4.0.5 on 2022-07-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
