# Generated by Django 4.0.5 on 2022-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='static/img/profile'),
        ),
    ]
