# Generated by Django 4.0.5 on 2022-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/profile/profile.jpg', upload_to='static/img/profile'),
        ),
    ]
